name: Build Release APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-apk:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.47.0"
          cache: true

      - name: Check Flutter
        run: |
          flutter --version
          dart --version

      - name: Check Flutter project
        working-directory: service_booking_app_flutter/service_booking_app
        run: |
          test -f pubspec.yaml
          echo "Flutter project found."

      - name: Get dependencies
        working-directory: service_booking_app_flutter/service_booking_app
        run: flutter pub get

      - name: Analyze project
        working-directory: service_booking_app_flutter/service_booking_app
        run: flutter analyze

      - name: Build Release APK
        working-directory: service_booking_app_flutter/service_booking_app
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: service-booking-release-apk
          path: service_booking_app_flutter/service_booking_app/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
